### ISSUE TITLE
Models not available

### ISSUE THREAD

**Issue by LeHenschel** [plattenmichael/DeepnCCA#1]
Hey Michael,

after reading about your work, I was very excited to try your pipeline on one of our datasets. Unfortunately, it seems like the weights of the pre-trained models are not available under the given address (Error message: "This shared file or folder link has been removed or is unavailable to you."). Is there an error with the given links or are there any other prerequisites to get access?

Thank you and have a nice weekend,
Leonie

**Comment by plattenmichael** [comment]
Hi Dr. LeHenschel,

Thank you for your interest! And thank you for catching this! My institution has changed its online cloud service, which is why the old links don't work anymore.

Here comes the new links, both with the password "corpus".
Corpus callosum model: https://owncloud.ki.se/index.php/s/T3gJPPvDMJrTGzX
Intracranial area model: https://owncloud.ki.se/index.php/s/1JCbG0LmtLdsAT1

I will also update the pipeline with this. 

Let me know if it doesn't work!

Best regards,
Michael

**Comment by LeHenschel** [comment]
Thank you Michael! The download is working now.

Kind regards,
Leonie
